### ISSUE TITLE
New Term - eventDurationValue

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#38]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: None

Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): eventDurationValue
* Term label (English, not normative): Event Duration Value
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): The numeric value for the duration of the dwc:Event.
* Usage comments (recommendations regarding content, etc., not normative): An eco:eventDurationValue must have a corresponding eco:eventDurationUnit.
* Examples (not normative): `1`; `30`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by timrobertson100** [comment]
Nit: I suggest modifying usage comments to include guidance about consistency with eventDate. E.g. 

> An eco:eventDuration must have a corresponding eco:eventDurationUnit [and must not contradict any ranges provided in eventDate]

**Comment by kingenloff** [comment]
Our ALA colleagues ask: Does the eventDuration/eventDurationUnit refer to the expected or actual duration?

They go on to note: Since dwc:eventDate (https://dwc.tdwg.org/terms/#dwc:verbatimEventDate) explicitly allows for start/end dates and times (eg. 2019-07-02T12:03:00/2019-07-02T12:15:00 has an event duration of 15 minutes, it would seem that the eventDuration is the expected duration.

Clarification between application of the two terms is necessary here.

**Comment by kingenloff** [comment]
Our ALA colleagues asked 'Does the **eventDuration**/**eventDurationUnit** refer to the expected or actual duration?'. They noted that 'Since **dwc:eventDate** explicitly allows for start/end dates and times (eg. 2019-07-02T12:03:00/2019-07-02T12:15:00 has an event duration of 15 minutes, it would seem that the **eventDuration** is the expected duration.'


I think there is some confusion here in what information is expected for the event timing terms. In this example, 15 min isn't the expected duration, it is the actual duration of the Event so **eco:eventDuration** is '15' and **eco:eventDurationUnit** is 'minutes.' This feedback suggests it would be useful to add explicit remarks in the comments of **eco:eventDuration** and **eco:eventDurationUnit** explaining how they relate to and complement **dwc:eventDate** (http://rs.tdwg.org/dwc/terms/eventDate).

**Comment by kingenloff** [comment]
Term name and comments updated to follow the recommended practice of pairing a termUnit and termValue. The term name updated from eventDuration to eventDurationValue pairs as recommended with eco:eventDurationUnit (https://github.com/tdwg/hc/issues/39).
