### ISSUE TITLE
New Term - inventoryTypes

### ISSUE THREAD

**Issue by tucotuco** [tdwg/hc#60]
## New term

* Submitter: Humboldt Extension Task Group
* Efficacy Justification (why is this term necessary?): Part of a package of terms in support of biological inventory data.
* Demand Justification (name at least two organizations that independently need this term): The Humboldt Extension Task Group proposing this term consists of numerous organizations. 
* Stability Justification (what concerns are there that this might affect existing implementations?): None
* Implications for dwciri: namespace (does this change affect a dwciri term version)?: Needs ecoiri: equivalent.
Proposed attributes of the new term:

* Term name (in lowerCamelCase for properties, UpperCamelCase for classes): inventoryTypes
* Term label (English, not normative): Inventory Types
* Organized in Class (e.g., Occurrence, Event, Location, Taxon): Event
* Definition of the term (normative): The types of search processes used to conduct the inventory.
* Usage comments (recommendations regarding content, etc., not normative): This term is only relevant if the dwc:Event represents an inventory. Recommended best practice is to use a controlled vocabulary. Recommended best practice is to separate multiple values in a list with space vertical bar space ( | ).
* Examples (not normative): `restricted search`; `open search`; `opportunistic search`; `adventitious`; `compilation`; `open search | opportunistic search`
* Refines (identifier of the broader term this term refines; normative): None
* Replaces (identifier of the existing term that would be deprecated and replaced by this term; normative): None
* ABCD 2.06 (XPATH of the equivalent term in ABCD or EFG; not normative): not in ABCD

**Comment by kingenloff** [comment]
Our ALA colleagues not that: The purpose of inventoryTypes as opposed to compilationType is unclear. This seems to be a common problem, as http://purl.obolibrary.org/obo/BCO_0000047 contains a similar comment.

**Comment by baskaufs** [comment]
I believe that we need to amend the Usage comments for this term from "Recommended best practice is to use a controlled vocabulary such as the terms included under the Biological Collections Ontology superclass 'taxonomic inventory process' (http://purl.obolibrary.org/obo/BCO_0000047)." to "Recommended best practice is to use a controlled vocabulary."

The major problem with this is that the labels for the BCO class terms in the ontology do not match up with the Examples given. So anyone who "follows their nose" as suggested in the Usage comments will be confused because what they find in the BCO labels will not match the strings in the example.

There is also the same issues with this suggestion that [stalled out the controlled vocabulary proposal for dwc:environmentalMaterial])https://github.com/tdwg/dwc/issues/40#issuecomment-824495721). The same possible solution would apply here: create an actual controlled vocabulary as we have for other Darwin Core terms, specify these (or other) controlled value strings for the terms, and link them to the BCO ontology as we have in the [ac:subjectPart](http://rs.tdwg.org/ac/doc/part/) and [ac:subjectOrientation](http://rs.tdwg.org/ac/doc/orient/) controlled vocabulary terms.
