### ISSUE TITLE
Need definition for "site" in the context of sampling events?

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#8]
Several terms in HC refer to "site(s)". During the first round of review we wondered if "site" should be defined beforehand. Although probably common jargon for ecologists, it may still lead to ambiguities. If a definition was needed, it would not need be in the definitions of the terms, but it could be included in the comments for each of them in the shape of "Site refers to....".

Here the relevant terms (original HC, current -as used now in IPT, and proposed by first round of review). For definitions please refer to csv terms file.

| HC original term | current term (IPT) | proposed term (first review round)|
| --- | --- | --- |
| number of separate sites | siteCount | siteCount |
| site nesting | siteNestingDescription | siteNestingDescription |
| site names | siteNames | verbatimSiteNames |
| site details | siteDetails | verbatimSiteDescription |

**Comment by yanisica** [comment]
Comments from Peter Brenton:

siteDetails: "Equivalent to **dwc:locationRemarks**. Defined for site object, but not used in observation or event records. 
ppsr:siteDescription is a summary description representing the static descriptive features of a site (eg. Spatial position relative to other things, slope, aspect, elevation, etc.). Dwc:locationRemarks may be used to augment siteDescription at event record level to reflect characteristics on ephemeral site features such as vegatation description, surface condition, etc."

See more info here on HC - PPSR mapping [here](https://docs.google.com/spreadsheets/d/1k2Pi02f6vBmkOdulzzUXKsKVFjbkyI-p/edit#gid=772770851)

**Comment by tucotuco** [comment]
I have lots of doubts about this series of terms, probably because in my mind I equate "site" with Darwin Core Location. A good definition for "site" seems crucial. I'll pick on Peter's comments to demonstrate my bias and ignorance.

> Comments from Peter Brenton:
> 
> siteCount: "This should be at the parentSite level and should not include nested subSites. ie. counted sites should represent only the unique places at which events took place, not the plots, transects and points within a site at which record-level data is collected."

In Darwin Core, a Location can be as granular as you want it to be, including plots, transects, and points. I have helped people to model Events hierarchies with distinct Locations even to distinct layers excavated from a forest floor. So, what is special about a Location that would warrant it being counted among sites?
 
> siteDetails: "Equivalent to **dwc:locationRemarks**. Defined for site object, but not used in observation or event records.
> ppsr:siteDescription is a summary description representing the static descriptive features of a site (eg. Spatial position relative to other things, slope, aspect, elevation, etc.). Dwc:locationRemarks may be used to augment siteDescription at event record level to reflect characteristics on ephemeral site features such as vegatation description, surface condition, etc."

The dwc:locationRemarks term should be used for the static features of a Location, not the ephemeral characteristics. Those should go in dwc:eventRemarks. But it sounds like there is a solid direct mapping between siteDetails and dwc:locationRemarks.
 
> siteNames: "A listing of site names is not very useful as often site naming conventions are specific to individual surveys and are only meaningful to those undertaking the survey. More useful would be a geometry for the spatialScope of all sites in a dataset. One would hope that site coordinates and ids are included with event records."

If the listing isn't very useful, I would opt for deprecation. Individual Locations can be given names in the dwc:locality field, so that useful meaning to those doing the survey need not be lost. Geometries can already be captured for every Event in dwc:footprintWKT.
 
> siteNestingDescription: "Probably part of ppsr:methodSpecification (below). Not sure that it is necessary to separate this out as a special attribute in it's own right. What value would this add?"
> 
> See more info here on HC - PPSR mapping [here](https://docs.google.com/spreadsheets/d/1k2Pi02f6vBmkOdulzzUXKsKVFjbkyI-p/edit#gid=772770851)

The only value I can imagine it having is if the explicit Location information was not given in the nested Events, but I am not an ecologist. Perhaps it could be useful for determining if the results of a study were relevant for a particular use based on the nesting design, but then it seems the concept would benefit from more rigor than just a description, and even utilize a controlled vocabulary.

**Comment by tucotuco** [comment]
The Extension proposal relies on Location through the Event without coining a new term for site.
