### ISSUE TITLE
Are "survey time blocks"-related terms really needed? in HC

### ISSUE THREAD

**Issue by pzermoglio** [tdwg/hc#9]
The following three terms in HC refer to "survey time blocks":

- Original HC `survey time blocks` definition:
   > The time blocks in which surveys were performed, either in sum or by site.

- Original HC `number of time units spent surveying in each block` definition:
   > The number of (months, days, hours) spent in each time block.

- Original HC `temporal unit` definition:
   >The temporal units described for the time block (months, days, years)

.
It has been suggested that these should be part of `dwc:samplingEffort`, currently defined as:
>The amount of effort expended during an Event. 

and with the following examples: `40 trap-nights`, `10 observer-hours`, `10 km by foot`, `30 km by car`

.
:scissors: :question:'s
  - Do we really need these three HC terms to be separate from sampling effort? 
  - How much granularity a) would we like to see, and b) are we likely to see in real data to justify separate terms? 
  - What would this information be used for? specially if very heterogeneous.

other :grey_question: 
  - Looking at those original definitions, how do we define time blocks exactly...?  (@robgur)

**Comment by tucotuco** [comment]
The definitions for these terms aren't very clear. The second and third ones together look like a duration for the blocks. I take it that a block is an uninterrupted time period. The first one, since it can be summed, must be a count since the second one already accounts for the other summable quantity - duration. In keeping with Darwin Core patterns, I would commit to a unit for the duration and have that be a part of the term name. I think that would serve to make quantities much more readily comparable. I would deprecate the temporal unit term.

If these are reasonable interpretations of the intention of the terms, and if these concepts are actually needed separately, then I would propose the following two term names and definitions:

surveyBlockCount - "The number of distinct survey periods within an Event." Example: 4
surveyBlockDurationInHours - "The duration (in hours) of survey periods within an Event." Example: 0.25

If they don't need to be separate, then the dwc:samplingEffort would work to capture the product of count and duration for a given event. Example matching those above: "4 blocks of 15 minutes each"

**Comment by pzermoglio** [comment]
Two new terms created from group discussion:

**eventDuration:** 
definition: Time spent sampling (in the unit reported in eventDurationUnit).
comments: A eventDuration should have a corresponding eventDurationUnit. 
examples: 1, 30

**eventDurationUnit**: 
definition: The temporal unit used to report eventDuration.
comments: A eventDurationUnit should have a corresponding eventDuration. 
examples: minutes, hours, days, months, years

**Comment by tucotuco** [comment]
The Extension proposal ended having eventDuration and eventDurationUnit.
